### ISSUE TITLE
Plugin causing fatal error

### ISSUE THREAD

**Issue by austinsparx** [BrianHenryIE/bh-wc-checkout-rate-limiter#12]
Firstly thank you for this plugin - hugely useful for me to help prevent card testing and it's much appreciated. I'm getting a fatal error on installation...

Warning: require_once(/www/wp-content/plugins/bh-wc-checkout-rate-limiter-1.2.0/vendor-prefixed/autoload.php): failed to open stream: No such file or directory in /www/wp-content/plugins/bh-wc-checkout-rate-limiter-1.2.0/autoload.php on line 39 Fatal error: require_once(): Failed opening required '/www/wp-content/plugins/bh-wc-checkout-rate-limiter-1.2.0/vendor-prefixed/autoload.php' (include_path='.:/usr/share/php') in /www/wp-content/plugins/bh-wc-checkout-rate-limiter-1.2.0/autoload.php on line 39

Not a huge amount of other plugins installed. 

PHP: 7.4
Wordpress: 6.02
WooCommerce: 7.0.0

**Comment by BrianHenryIE** [comment]
Hey,
Looks like you've downloaded the git repo and tried installing that as the plugin, but haven't built the project.

Easiest option is to download from the [releases page](https://github.com/BrianHenryIE/bh-wc-checkout-rate-limiter/releases)

**Comment by austinsparx** [comment]
Ah sorry thought I had done that - all sorted thanks for fast reply and for the plugin!

**Comment by BrianHenryIE** [comment]
I'll add a try/catch around the autoload include and show an admin notice linking to the releases page.
